apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tines
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/mpursley/k8s_services.git
    targetRevision: main
    path: charts/tines
  destination:
    server: https://kubernetes.default.svc
    namespace: tines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
