apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services-landing-page-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mpursley/k8s_services.git
    targetRevision: HEAD
    path: charts/services-landing-page-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
